//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.08 at 10:16:40 AM GMT+01:00 
//


package es.us.isa.ppinot.xmlClasses.ppinot;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tAggregatedMeasure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAggregatedMeasure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isa.us.es/ppinot}tMeasure">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.isa.us.es/ppinot}baseMeasure"/>
 *       &lt;/sequence>
 *       &lt;attribute name="aggregationfunction" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="samplingfrequency" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAggregatedMeasure", propOrder = {
    "baseMeasure"
})
public class TAggregatedMeasure
    extends TMeasure
{

    @XmlElementRef(name = "baseMeasure", namespace = "http://www.isa.us.es/ppinot", type = JAXBElement.class)
    protected JAXBElement<? extends TBaseMeasure> baseMeasure;
    @XmlAttribute
    protected String aggregationfunction;
    @XmlAttribute
    protected String samplingfrequency;

    /**
     * Gets the value of the baseMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TDataPropertyConditionMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TStateConditionMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TDataMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TBaseMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TTimeMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TCountMeasure }{@code >}
     *     
     */
    public JAXBElement<? extends TBaseMeasure> getBaseMeasure() {
        return baseMeasure;
    }

    /**
     * Sets the value of the baseMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TDataPropertyConditionMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TStateConditionMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TDataMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TBaseMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TTimeMeasure }{@code >}
     *     {@link JAXBElement }{@code <}{@link TCountMeasure }{@code >}
     *     
     */
    public void setBaseMeasure(JAXBElement<? extends TBaseMeasure> value) {
        this.baseMeasure = ((JAXBElement<? extends TBaseMeasure> ) value);
    }

    /**
     * Gets the value of the aggregationfunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggregationfunction() {
        if (aggregationfunction == null) {
            return "";
        } else {
            return aggregationfunction;
        }
    }

    /**
     * Sets the value of the aggregationfunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggregationfunction(String value) {
        this.aggregationfunction = value;
    }

    /**
     * Gets the value of the samplingfrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplingfrequency() {
        if (samplingfrequency == null) {
            return "";
        } else {
            return samplingfrequency;
        }
    }

    /**
     * Sets the value of the samplingfrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplingfrequency(String value) {
        this.samplingfrequency = value;
    }

}
