//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.08 at 10:16:40 AM GMT+01:00 
//


package es.us.isa.ppinot.xmlClasses.ppinot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tIsGroupedBy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tIsGroupedBy">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isa.us.es/ppinot}tMeasureConnector">
 *       &lt;attribute name="dataContentSelection" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tIsGroupedBy")
public class TIsGroupedBy
    extends TMeasureConnector
{

    @XmlAttribute
    protected String dataContentSelection;

    /**
     * Gets the value of the dataContentSelection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataContentSelection() {
        if (dataContentSelection == null) {
            return "";
        } else {
            return dataContentSelection;
        }
    }

    /**
     * Sets the value of the dataContentSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataContentSelection(String value) {
        this.dataContentSelection = value;
    }

}
