//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.08 at 10:16:40 AM GMT+01:00 
//


package es.us.isa.isabpm.ppinot.xmlClasses.ppinot;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tPpiset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPpiset">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.isa.us.es/ppinot}baseMeasure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.isa.us.es/ppinot}aggregatedMeasure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.isa.us.es/ppinot}derivedMeasure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.isa.us.es/ppinot}measureConnector" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.isa.us.es/ppinot}ppi" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPpiset", propOrder = {
    "baseMeasure",
    "aggregatedMeasure",
    "derivedMeasure",
    "measureConnector",
    "ppi"
})
public class TPpiset {

    @XmlElementRef(name = "baseMeasure", namespace = "http://www.isa.us.es/ppinot", type = JAXBElement.class)
    protected List<JAXBElement<? extends TBaseMeasure>> baseMeasure;
    protected List<TAggregatedMeasure> aggregatedMeasure;
    @XmlElementRef(name = "derivedMeasure", namespace = "http://www.isa.us.es/ppinot", type = JAXBElement.class)
    protected List<JAXBElement<? extends TDerivedMeasure>> derivedMeasure;
    @XmlElementRef(name = "measureConnector", namespace = "http://www.isa.us.es/ppinot", type = JAXBElement.class)
    protected List<JAXBElement<? extends TMeasureConnector>> measureConnector;
    protected List<TPpi> ppi;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the baseMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baseMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaseMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TDataPropertyConditionMeasure }{@code >}
     * {@link JAXBElement }{@code <}{@link TStateConditionMeasure }{@code >}
     * {@link JAXBElement }{@code <}{@link TDataMeasure }{@code >}
     * {@link JAXBElement }{@code <}{@link TBaseMeasure }{@code >}
     * {@link JAXBElement }{@code <}{@link TTimeMeasure }{@code >}
     * {@link JAXBElement }{@code <}{@link TCountMeasure }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TBaseMeasure>> getBaseMeasure() {
        if (baseMeasure == null) {
            baseMeasure = new ArrayList<JAXBElement<? extends TBaseMeasure>>();
        }
        return this.baseMeasure;
    }

    /**
     * Gets the value of the aggregatedMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggregatedMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggregatedMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAggregatedMeasure }
     * 
     * 
     */
    public List<TAggregatedMeasure> getAggregatedMeasure() {
        if (aggregatedMeasure == null) {
            aggregatedMeasure = new ArrayList<TAggregatedMeasure>();
        }
        return this.aggregatedMeasure;
    }

    /**
     * Gets the value of the derivedMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the derivedMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDerivedMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TDerivedMeasure }{@code >}
     * {@link JAXBElement }{@code <}{@link TDerivedMultiInstanceMeasure }{@code >}
     * {@link JAXBElement }{@code <}{@link TDerivedSingleInstanceMeasure }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TDerivedMeasure>> getDerivedMeasure() {
        if (derivedMeasure == null) {
            derivedMeasure = new ArrayList<JAXBElement<? extends TDerivedMeasure>>();
        }
        return this.derivedMeasure;
    }

    /**
     * Gets the value of the measureConnector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measureConnector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasureConnector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TUses }{@code >}
     * {@link JAXBElement }{@code <}{@link TAggregates }{@code >}
     * {@link JAXBElement }{@code <}{@link TTimeConnector }{@code >}
     * {@link JAXBElement }{@code <}{@link TAppliesToDataConnector }{@code >}
     * {@link JAXBElement }{@code <}{@link TIsGroupedBy }{@code >}
     * {@link JAXBElement }{@code <}{@link TMeasureConnector }{@code >}
     * {@link JAXBElement }{@code <}{@link TAppliesToElementConnector }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends TMeasureConnector>> getMeasureConnector() {
        if (measureConnector == null) {
            measureConnector = new ArrayList<JAXBElement<? extends TMeasureConnector>>();
        }
        return this.measureConnector;
    }

    /**
     * Gets the value of the ppi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ppi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPpi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TPpi }
     * 
     * 
     */
    public List<TPpi> getPpi() {
        if (ppi == null) {
            ppi = new ArrayList<TPpi>();
        }
        return this.ppi;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
