//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.08 at 10:16:40 AM GMT+01:00 
//


package es.us.isa.isabpm.ppinot.xmlClasses.ppinot;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTimeMeasure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTimeMeasure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.isa.us.es/ppinot}tBaseMeasure">
 *       &lt;attribute name="timeMeasureType" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="singleInstanceAggFunction" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTimeMeasure")
public class TTimeMeasure
    extends TBaseMeasure
{

    @XmlAttribute
    protected String timeMeasureType;
    @XmlAttribute
    protected String singleInstanceAggFunction;

    /**
     * Gets the value of the timeMeasureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeMeasureType() {
        if (timeMeasureType == null) {
            return "";
        } else {
            return timeMeasureType;
        }
    }

    /**
     * Sets the value of the timeMeasureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeMeasureType(String value) {
        this.timeMeasureType = value;
    }

    /**
     * Gets the value of the singleInstanceAggFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSingleInstanceAggFunction() {
        if (singleInstanceAggFunction == null) {
            return "";
        } else {
            return singleInstanceAggFunction;
        }
    }

    /**
     * Sets the value of the singleInstanceAggFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSingleInstanceAggFunction(String value) {
        this.singleInstanceAggFunction = value;
    }

}
