		var loadTarget = {
			value: 0,
			contained: {minRef: -10},
			value:1,
			contained: {maxRef: 10},
			value:2,
			contained: {minequalRef: -10},
			value:3,
			contained: {maxequalRef:10},
		};
		
   		$("#Target").linguisticPattern("The PPI value must", options, loadTarget);
   		
		var load = {
			Time:{
		    	            value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0 contained: {activityName: {value:1},activityState: {value: 1}}}},
	                        value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 1}}}},
					        value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 2}}}},
		                     value: 0, contained: {startEvent: {value: 0,contained: {activityName: {value:0},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:0}}}},
							value: 0, contained: {startEvent: {value: 0,contained: {activityName: {value:0},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:1}}}},
							value: 0, contained: {startEvent: {value: 0,contained: {activityName: {value:0},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:2}}}},
							
                            value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1},activityState: {value: 1}}}},
	                        value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 1}}}},
					        value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 2}}}},
					      
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:1},activityState: {value: 1}}}},
	                        value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2},activityState: {value: 1}}}},
					        value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:2},activityState: {value: 2}}}},
					        
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0 contained: {activityName: {value:1},activityState: {value: 1}}}},
	                        value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 1}}}},
					        value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 2}}}},
					        value: 0, contained: {startEvent: {value: 1,contained: {activityName: {value:0},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:0}}}},
							value: 0, contained: {startEvent: {value: 1,contained: {activityName: {value:0},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:1}}}},
							value: 0, contained: {startEvent: {value: 1,contained: {activityName: {value:0},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:2}}}},
							
					        value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1},activityState: {value: 1}}}},
	                        value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 1}}}},
					        value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 2}}}},
					        
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:1},activityState: {value: 1}}}},
	                        value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 2}}}},
						    value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2},activityState: {value: 1}}}},
					        value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:2},activityState: {value: 2}}}},
					        value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
						
					        value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0 contained: {activityName: {value:1},activityState: {value: 1}}}},
	                        value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 1}}}},
					        value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 2}}}},
					        value: 0, contained: {startEvent: {value: 2,contained: {activityName: {value:0},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:0}}}},
							value: 0, contained: {startEvent: {value: 2,contained: {activityName: {value:0},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:1}}}},
							value: 0, contained: {startEvent: {value: 2,contained: {activityName: {value:0},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:2}}}},
							
					        value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1},activityState: {value: 1}}}},
	                        value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 1}}}},
					        value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 2}}}},
					        
						    value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:1},activityState: {value: 1}}}},
	                        value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2},activityState: {value: 1}}}},
					        value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:2},activityState: {value: 2}}}},
					        
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0 contained: {activityName: {value:1},activityState: {value: 1}}}},
		                    value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 1}}}},
						    value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 2}}}},
		                    value: 0, contained: {startEvent: {value: 0,contained: {activityName: {value:1},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:0}}}},
							value: 0, contained: {startEvent: {value: 0,contained: {activityName: {value:1},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:1}}}},
							value: 0, contained: {startEvent: {value: 0,contained: {activityName: {value:1},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:2}}}},
								
	                        value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1},activityState: {value: 1}}}},
		                    value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 1}}}},
						    value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 2}}}},
						    
						    value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:1},activityState: {value: 1}}}},
		                    value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2},activityState: {value: 1}}}},
						    value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:2},activityState: {value: 2}}}},
						   
						    value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0 contained: {activityName: {value:1},activityState: {value: 1}}}},
		                    value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 1}}}},
						    value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 2}}}},
						    value: 0, contained: {startEvent: {value: 1,contained: {activityName: {value:1},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:0}}}},
							value: 0, contained: {startEvent: {value: 1,contained: {activityName: {value:1},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:1}}}},
							value: 0, contained: {startEvent: {value: 1,contained: {activityName: {value:1},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:2}}}},
								
						    value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1},activityState: {value: 1}}}},
		                    value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 1}}}},
						    value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 2}}}},
						    
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:1},activityState: {value: 1}}}},
		                    value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2},activityState: {value: 1}}}},
						    value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:2},activityState: {value: 2}}}},
						     
							value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0 contained: {activityName: {value:1},activityState: {value: 1}}}},
		                    value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 1}}}},
						    value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 2}}}},
                            value: 0, contained: {startEvent: {value: 2,contained: {activityName: {value:1},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:0}}}},
							value: 0, contained: {startEvent: {value: 2,contained: {activityName: {value:1},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:1}}}},
							value: 0, contained: {startEvent: {value: 2,contained: {activityName: {value:1},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:2}}}},
								
						    value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1},activityState: {value: 1}}}},
		                    value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 2}}}},
						    value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 1}}}},
						    value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 2}}}},
						    
						    value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:1},activityState: {value: 1}}}},
		                    value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2},activityState: {value: 1}}}},
						    value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:2},activityState: {value: 2}}}},
						    
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0 contained: {activityName: {value:1},activityState: {value: 1}}}},
			                value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 1}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0,contained: {activityName: {value:2},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:0}}}},
							value: 0, contained: {startEvent: {value: 0,contained: {activityName: {value:2},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:1}}}},
							value: 0, contained: {startEvent: {value: 0,contained: {activityName: {value:2},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:2}}}},
									
		                    value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1},activityState: {value: 1}}}},
			                value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 1}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 2}}}},
							
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:1},activityState: {value: 1}}}},
			                value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2},activityState: {value: 1}}}},
							value: 0, contained: {startEvent: {value: 0, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:2},activityState: {value: 2}}}},
							
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0 contained: {activityName: {value:1},activityState: {value: 1}}}},
			                value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 1}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 1,contained: {activityName: {value:2},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:0}}}},
							value: 0, contained: {startEvent: {value: 1,contained: {activityName: {value:2},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:1}}}},
							value: 0, contained: {startEvent: {value: 1,contained: {activityName: {value:2},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:2}}}},
									
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1},activityState: {value: 1}}}},
			                value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 1}}}},
							value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 2}}}},
							
	                         
			                 value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							 value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							 value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:1},activityState: {value: 1}}}},
			                 value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							 value:0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2},activityState: {value: 1}}}},
							 value: 0, contained: {startEvent: {value: 1, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:2},activityState: {value: 2}}}},
							
						     value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							 value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0 contained: {activityName: {value:1},activityState: {value: 1}}}},
			                 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							 value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 1}}}},
							 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 0, contained: {activityName: {value:2},activityState: {value: 2}}}},
							 value: 0, contained: {startEvent: {value: 2,contained: {activityName: {value:2},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:0}}}},
							 value: 0, contained: {startEvent: {value: 2,contained: {activityName: {value:2},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:1}}}},
							 value: 0, contained: {startEvent: {value: 2,contained: {activityName: {value:2},activityState: {value: 0}}}, endEvent: {value: 3, contained: {activityName: {value:2}}}},
									
							 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							 value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1},activityState: {value: 1}}}},
			                 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							 value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 1}}}},
							 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 1, contained: {activityName: {value:2},activityState: {value: 2}}}},
							 
							 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 1}}}},
							 value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:0}, activityState: {value: 2}}}},
							 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:1},activityState: {value: 1}}}},
			                 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:1}, activityState: {value: 2}}}},
							 value:0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2, contained: {activityName: {value:2},activityState: {value: 1}}}},
							 value: 0, contained: {startEvent: {value: 2, contained: {activityName: {value:2}, activityState: {value: 0}}}, endEvent: {value: 2 contained: {activityName: {value:2},activityState: {value: 2}}}},
						},
			Count: {
				    value: 1, contained:{event:{value:0, contained:{activityName:{value:0}, activityState:{value:0}}}},
				    value: 1, contained:{event:{value:0, contained:{activityName:{value:0}, activityState:{value:1}}}},
				    value: 1, contained:{event:{value:0, contained:{activityName:{value:0}, activityState:{value:2}}}},
				    value: 1, contained:{event:{value:0, contained:{activityName:{value:1}, activityState:{value:0}}}},
				    value: 1, contained:{event:{value:0, contained:{activityName:{value:1}, activityState:{value:1}}}},
				    value: 1, contained:{event:{value:0, contained:{activityName:{value:1}, activityState:{value:2}}}},
				    value: 1, contained:{event:{value:0, contained:{activityName:{value:2}, activityState:{value:0}}}},
				    value: 1, contained:{event:{value:0, contained:{activityName:{value:2}, activityState:{value:1}}}},
				    value: 1, contained:{event:{value:0, contained:{activityName:{value:2}, activityState:{value:2}}}},
				    
				    value: 1, contained:{event:{value:1, contained:{activityName:{value:0}, activityState:{value:0}}}},
				    value: 1, contained:{event:{value:1, contained:{activityName:{value:0}, activityState:{value:1}}}},
				    value: 1, contained:{event:{value:1, contained:{activityName:{value:0}, activityState:{value:2}}}},
				    value: 1, contained:{event:{value:1, contained:{activityName:{value:1}, activityState:{value:0}}}},
				    value: 1, contained:{event:{value:1, contained:{activityName:{value:1}, activityState:{value:1}}}},
				    value: 1, contained:{event:{value:1, contained:{activityName:{value:1}, activityState:{value:2}}}},
				    value: 1, contained:{event:{value:1, contained:{activityName:{value:2}, activityState:{value:0}}}},
				    value: 1, contained:{event:{value:1, contained:{activityName:{value:2}, activityState:{value:1}}}},
				    value: 1, contained:{event:{value:1, contained:{activityName:{value:2}, activityState:{value:2}}}},
				    
				    value: 1, contained:{event:{value:2, contained:{activityName:{value:0}, activityState:{value:0}}}},
				    value: 1, contained:{event:{value:2, contained:{activityName:{value:0}, activityState:{value:1}}}},
				    value: 1, contained:{event:{value:2, contained:{activityName:{value:0}, activityState:{value:2}}}},
				    value: 1, contained:{event:{value:2, contained:{activityName:{value:1}, activityState:{value:0}}}},
				    value: 1, contained:{event:{value:2, contained:{activityName:{value:1}, activityState:{value:1}}}},
				    value: 1, contained:{event:{value:2, contained:{activityName:{value:1}, activityState:{value:2}}}},
				    value: 1, contained:{event:{value:2, contained:{activityName:{value:2}, activityState:{value:0}}}},
				    value: 1, contained:{event:{value:2, contained:{activityName:{value:2}, activityState:{value:1}}}},
				    value: 1, contained:{event:{value:2, contained:{activityName:{value:2}, activityState:{value:2}}}},
				    
				    value: 1, contained:{event:{value:3, contained:{activityName:{value:0}}}},
				    value: 1, contained:{event:{value:3, contained:{activityName:{value:0}}}},
				    value: 1, contained:{event:{value:3, contained:{activityName:{value:0}}}},
				    value: 1, contained:{event:{value:3, contained:{activityName:{value:1}}}},
				    value: 1, contained:{event:{value:3, contained:{activityName:{value:1}}}},
				    value: 1, contained:{event:{value:3, contained:{activityName:{value:1}}}},
				    value: 1, contained:{event:{value:3, contained:{activityName:{value:2}}}},
				    value: 1, contained:{event:{value:3, contained:{activityName:{value:2}}}},
				    value: 1, contained:{event:{value:3, contained:{activityName:{value:2}}}},
				  },
StateConditionMeasure:{
	                value:2, contained:{activityType:{value:0},activityName:{value:0},activityState:{value:0}},
	                value:2, contained:{activityType:{value:0},activityName:{value:0},activityState:{value:1}},
	                value:2, contained:{activityType:{value:0},activityName:{value:0},activityState:{value:2}},
	                value:2, contained:{activityType:{value:0},activityName:{value:1},activityState:{value:0}},
	                value:2, contained:{activityType:{value:0},activityName:{value:1},activityState:{value:1}},
	                value:2, contained:{activityType:{value:0},activityName:{value:1},activityState:{value:2}},
	                value:2, contained:{activityType:{value:0},activityName:{value:2},activityState:{value:0}},
	                value:2, contained:{activityType:{value:0},activityName:{value:2},activityState:{value:1}},
	                value:2, contained:{activityType:{value:0},activityName:{value:2},activityState:{value:2}},
	                
	                value:2, contained:{activityType:{value:1},activityName:{value:0},activityState:{value:0}},
	                value:2, contained:{activityType:{value:1},activityName:{value:0},activityState:{value:1}},
	                value:2, contained:{activityType:{value:1},activityName:{value:0},activityState:{value:2}},
	                value:2, contained:{activityType:{value:1},activityName:{value:1},activityState:{value:0}},
	                value:2, contained:{activityType:{value:1},activityName:{value:1},activityState:{value:1}},
	                value:2, contained:{activityType:{value:1},activityName:{value:1},activityState:{value:2}},
	                value:2, contained:{activityType:{value:1},activityName:{value:2},activityState:{value:0}},
	                value:2, contained:{activityType:{value:1},activityName:{value:2},activityState:{value:1}},
	                value:2, contained:{activityType:{value:1},activityName:{value:2},activityState:{value:2}},
	                
	                value:2, contained:{activityType:{value:2},activityName:{value:0},activityState:{value:0}},
	                value:2, contained:{activityType:{value:2},activityName:{value:0},activityState:{value:1}},
	                value:2, contained:{activityType:{value:2},activityName:{value:0},activityState:{value:2}},
	                value:2, contained:{activityType:{value:2},activityName:{value:1},activityState:{value:0}},
	                value:2, contained:{activityType:{value:2},activityName:{value:1},activityState:{value:1}},
	                value:2, contained:{activityType:{value:2},activityName:{value:1},activityState:{value:2}},
	                value:2, contained:{activityType:{value:2},activityName:{value:2},activityState:{value:0}},
	                value:2, contained:{activityType:{value:2},activityName:{value:2},activityState:{value:1}},
	                value:2, contained:{activityType:{value:2},activityName:{value:2},activityState:{value:2}},
	                
	                value:2, contained:{activityType:{value:3},activityName:{value:0}},
	                value:2, contained:{activityType:{value:3},activityName:{value:1}},
	                value:2, contained:{activityType:{value:3},activityName:{value:2}},
	          },
	  DataPropertyCondition:{value:3, contained: {DataObjectName:{value:0}, ConditionDataObjectPropertie:{value:0}}},  
      Data: {value:4, contained: {DataObjectPropertyName:{value:0}, DataObjectName{value:0}}},
	  AggregatedMeasure:{
		                   value:5, contained:{Aggregate:{value: 0}, MeasureForAgg:{contained:{Time}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
		                   value:5, contained:{Aggregate:{value: 0}, MeasureForAgg:{contained:{count}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
		                   value:5, contained:{Aggregate:{value: 0}, MeasureForAgg:{contained:{StateConditionMeasure}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
		                   value:5, contained:{Aggregate:{value: 0}, MeasureForAgg:{contained:{DataPropertyCondition}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
		                   value:5, contained:{Aggregate:{value: 0}, MeasureForAgg:{contained:{Data}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
		                   value:5, contained:{Aggregate:{value: 0}, MeasureForAgg:{contained:{{DerivedMeasure}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
		                   
		                   value:5, contained:{Aggregate:{value: 1}, MeasureForAgg:{contained:{Time}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 1}, MeasureForAgg:{contained:{count}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 1}, MeasureForAgg:{contained:{StateConditionMeasure}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 1}, MeasureForAgg:{contained:{DataPropertyCondition}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 1}, MeasureForAgg:{contained:{Data}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 1}, MeasureForAgg:{contained:{{DerivedMeasure}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			            	   
			               value:5, contained:{Aggregate:{value: 2}, MeasureForAgg:{contained:{Time}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 2}, MeasureForAgg:{contained:{count}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 2}, MeasureForAgg:{contained:{StateConditionMeasure}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 2}, MeasureForAgg:{contained:{DataPropertyCondition}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 2}, MeasureForAgg:{contained:{Data}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 2}, MeasureForAgg:{contained:{{DerivedMeasure}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			            	   
			               value:5, contained:{Aggregate:{value: 3}, MeasureForAgg:{contained:{Time}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 3}, MeasureForAgg:{contained:{count}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 3}, MeasureForAgg:{contained:{StateConditionMeasure}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 3}, MeasureForAgg:{contained:{DataPropertyCondition}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 3}, MeasureForAgg:{contained:{Data}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			               value:5, contained:{Aggregate:{value: 3}, MeasureForAgg:{contained:{{DerivedMeasure}}, DataObjectPropertyName:{value:0}, DataObjectName:{value:0}},
			            },
			            
	  DerivedMeasure:{
		               value:6, contained:{{expresion}, {parametros}, MeasureForDer:{contained:{{Time}}}},
		               value:6, contained:{{expresion}, {parametros}, MeasureForDer:{contained:{{count}}}},
		               value:6, contained:{{expresion}, {parametros}, MeasureForDer:{contained:{{StateConditionMeasure}}}},
		               value:6, contained:{{expresion}, {parametros}, MeasureForDer:{contained:{{Data}}}},
		               value:6, contained:{{expresion}, {parametros}, MeasureForDer:{contained:{{AggregatedMeasure}}}},
		             }
	  }
			
		};

   		$("#Definition").linguisticPattern("The PPI is defined as", measureOptions, load);

   		console.log("Hoal mudno");
   		var valorDato = $("#Definition").data("value");
   		console.log(valorDato);
    });
